Update all scripts.
+ Sync submodule: uhub.

diff --git a/Debian/elmer-doc/automatic_update_elmer-doc b/Debian/elmer-doc/automatic_update_elmer-doc
--- a/Debian/elmer-doc/automatic_update_elmer-doc
+++ b/Debian/elmer-doc/automatic_update_elmer-doc
@@ -11,6 +11,9 @@ export PACKAGE="elmer-doc"
 #export NEW_VER=2013.02.01
 #export NEW_VER=2011.09.06
 
+export A_TYPE="gz"
+
+
 # experimental unstable
 export MAIN_DIST="experimental"
 
@@ -24,14 +27,14 @@ GetOldVersion
 export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*.svn.\([0-9]\+\).dfsg.*$/\1/")
 
 
-# Find new version
-export LAST_MOD=$(curl -I 'ftp://ftp.funet.fi/index/elmer/doc/ElmerDocumentation.tar.gz' 2>&1 | sed -ne "s/^.*Last-Modified: \(.*\) GMT.*$/\1/p")
-if [ -z "${LAST_MOD}" ]; then
-    echo "Failed to define current version."
-    exit 1
-fi
-if [ -z "${NEW_VER}" ]; then
-    export NEW_VER=$(date -d "${LAST_MOD}" "+%Y.%m.%d")
+# Get new version
+if GetNewVersion "${@}"; then
+    LAST_MOD=$(curl -I 'ftp://ftp.funet.fi/index/elmer/doc/ElmerDocumentation.tar.gz' 2>&1 | sed -ne "s/^.*Last-Modified: \(.*\) GMT.*$/\1/p")
+    if [ -z "${LAST_MOD}" ]; then
+        echo "Failed to define current version."
+        exit 1
+    fi
+    NEW_VER=$(date -d "${LAST_MOD}" "+%Y.%m.%d")
 fi
 export NEW_VER_FULL=${NEW_VER}${SFX}
 
@@ -48,17 +51,10 @@ PrintVersions "${@}"
 CheckVersions
 
 
-# Get the sources
-if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.gz" ]; then
-    "${PKG_DIR}/${PACKAGE}-debian/debian/rules" "get-orig-source" || exit 1
-fi
+# Get sources
+GetSources
 
 
-export UPDATE_STRING="New upstream release."
-
-export A_TYPE="gz"
-export D_ARGS="xzf"
-
-# Launch common script for updating packages and uploading them to mentors.debian.net
+# Launch common script for updating of packages
 source "${MAIN_DIR}/Debian/updating_packages"
 
diff --git a/Launchpad/elmer-doc/automatic_update_elmer-doc b/Launchpad/elmer-doc/automatic_update_elmer-doc
--- a/Launchpad/elmer-doc/automatic_update_elmer-doc
+++ b/Launchpad/elmer-doc/automatic_update_elmer-doc
@@ -10,6 +10,8 @@ export PACKAGE="elmer-doc"
 
 #export NEW_VER=2013.02.01
 
+export A_TYPE="gz"
+
 
 # Launch common script for setting variables
 source "${MAIN_DIR}/Launchpad/setting_variables"
@@ -20,14 +22,14 @@ GetOldVersion
 export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*.svn.\([0-9]\+\).dfsg.*$/\1/")
 
 
-# Find new version
-export LAST_MOD=$(curl -I 'ftp://ftp.funet.fi/index/elmer/doc/ElmerDocumentation.tar.gz' 2>&1 | sed -ne "s/^.*Last-Modified: \(.*\) GMT.*$/\1/p")
-if [ -z "${LAST_MOD}" ]; then
-    echo "Failed to define current version."
-    exit 1
-fi
-if [ -z "${NEW_VER}" ]; then
-    export NEW_VER=$(date -d "${LAST_MOD}" "+%Y.%m.%d")
+# Get new version
+if GetNewVersion "${@}"; then
+    LAST_MOD=$(curl -I 'ftp://ftp.funet.fi/index/elmer/doc/ElmerDocumentation.tar.gz' 2>&1 | sed -ne "s/^.*Last-Modified: \(.*\) GMT.*$/\1/p")
+    if [ -z "${LAST_MOD}" ]; then
+        echo "Failed to define current version."
+        exit 1
+    fi
+    NEW_VER=$(date -d "${LAST_MOD}" "+%Y.%m.%d")
 fi
 export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}
 
@@ -50,9 +52,6 @@ GetSources
 
 export DESTINATION="elmerfem"
 
-export A_TYPE="gz"
-export D_ARGS="xzf"
-
-# Launch common script for updating packages and uploading them to Launchpad
+# Launch common script for updating of packages and uploading them to Launchpad
 source "${MAIN_DIR}/Launchpad/updating_packages"
 
