psimedia script and submodule were updated. eiskaltdcpp-unstable, eiskaltdcpp-unstable and q4wine-unstable submodules were updated. deb-packages.html was updated.

diff --git a/Debian/setting_variables b/Debian/setting_variables
--- a/Debian/setting_variables
+++ b/Debian/setting_variables
@@ -47,6 +47,16 @@ DisplayVersions()
 }
 
 
+# Display versions for unstable packages
+DisplayVersionsUnstable()
+{
+    echo "Old  commit: ${OLD_COMMIT}"
+    echo "Last commit: ${LAST_COMMIT}"
+    echo "OLD_VER_FULL = ${OLD_VER_FULL}"
+    echo "NEW_VER_FULL = ${NEW_VER_FULL}"
+}
+
+
 # Print versions
 PrintVersions()
 {
@@ -75,6 +85,34 @@ PrintVersions()
 }
 
 
+# Print versions for unstable packages
+PrintVersionsUnstable()
+{
+if [ "${1}" = "print-versions" ]; then
+    if [ -z "${2}" ]; then
+        echo "File name must be not empty!"
+        exit 1
+    else
+        HTML_FILE="${2}"
+        echo "<td style=\"font-weight: bold;\">" >> "${HTML_FILE}"
+        echo "${PACKAGE}" >> "${HTML_FILE}"
+        echo "</td>" >> "${HTML_FILE}"
+        echo "<td>" >> "${HTML_FILE}"
+        echo "${OLD_VER_FULL}" >> "${HTML_FILE}"
+        echo "</td>" >> "${HTML_FILE}"
+        if [ "${LAST_COMMIT}" != "${OLD_COMMIT}" ]; then
+            echo "<td class=\"color-outdated\">" >> "${HTML_FILE}"
+        else
+            echo "<td class=\"color-actual\">" >> "${HTML_FILE}"
+        fi
+        echo "${NEW_VER_FULL}" >> "${HTML_FILE}"
+        echo "</td>" >> "${HTML_FILE}"
+        exit 0
+    fi
+fi
+}
+
+
 # Check versions
 CheckVersions()
 {
@@ -96,6 +134,34 @@ CheckVersions()
         else
             if [ "${SFX}" = "-1" ]; then
                 echo "Now SFX = ${SFX} but OLD_SFX = ${OLD_SFX}.";
+                echo "Upgrading is not required.";
+                exit 0;
+            fi
+        fi
+    fi
+}
+
+
+# Check versions for unstable packages
+CheckVersionsUnstable()
+{
+    if [ -z "${OLD_COMMIT}" ]; then
+        echo "OLD_COMMIT is empty!";
+        exit 1;
+    elif [ -z "${LAST_COMMIT}" ]; then
+        echo "LAST_COMMIT is empty!";
+        exit 1;
+    elif [ -z ${CUR_VER} ]; then
+        echo "CUR_VER is empty!";
+        exit 1;
+    else
+        if [ "${LAST_COMMIT}" != "${OLD_COMMIT}" ]; then
+            if [ "${SFX}" != "-1" ]; then
+                echo "Now SFX = ${SFX} but must be '-1' for a new release!";
+                exit 0;
+            fi
+        else
+            if [ "${SFX}" = "-1" ]; then
                 echo "Upgrading is not required.";
                 exit 0;
             fi
