Update Debian scripts.

diff --git a/Debian/updating_single-diff_packages b/Debian/updating_single-diff_packages
--- a/Debian/updating_single-diff_packages
+++ b/Debian/updating_single-diff_packages
@@ -1,13 +1,6 @@
 #!/bin/bash
-
-# This is the common script for updating packages and uploading them to mentors.debian.net
 #
-# It make such actions:
-# 1) Update changelog.
-# 2) Prepare sources to upload.
-#    Build the package and check it using lintian (optional)
-# 3) Upload sources to mentors.debian.net
-
+# Common script for updating of old style packages
 
 if [ -z "${PACKAGE}" ]; then
     echo "Error: PACKAGE variable is empty!";
@@ -17,10 +10,21 @@ elif [ -z "${NEW_VER}" ]; then
     exit 1;
 fi
 
-if [ -z "${A_TYPE}" ]; then
-    export A_TYPE="bz2"
+case "${A_TYPE}" in
+"gz")
+    export D_ARGS="xzf"
+;;
+"bz2")
     export D_ARGS="xjf"
-fi
+;;
+"xz")
+    export D_ARGS="xJf"
+;;
+*)
+    echo "Tarball type is not defined!"
+    exit 1
+;;
+esac
 
 if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.${A_TYPE}" ]; then
     echo "File ${PACKAGE}_${NEW_VER}.orig.tar.${A_TYPE} is not found.";
@@ -37,19 +41,23 @@ fi
 
 if [ "${1}" = "clean" ]; then
     export CLEAN_BUILD="true"
+elif [ "${1}" = "fast" ]; then
+    export FAST_UPLOAD="true"
+fi
+
+if [ "${2}" = "new" ]; then
+    export TARGETED_TO_NEW_QUEUE="true"
 fi
 
 echo "Updating is started."
-
-export DEBEMAIL="Boris Pek <tehnick@debian.org>"
 
 rm -rf "${DIR_NAME}" "${PACKAGE}_${NEW_VER}-"*
 
 tar "${D_ARGS}" "${PACKAGE}_${NEW_VER}.orig.tar.${A_TYPE}"
 rm -rf "${DIR_NAME}/debian"
-cp -af "${PKG_DIR}/${PACKAGE}-debian"/* "${DIR_NAME}"/
+cp -rf "${PKG_DIR}/${PACKAGE}-debian/debian" "${DIR_NAME}/debian"
 
-if [ -d "${OLD_DIR_NAME}" ]; then
+if [ -d "${OLD_DIR_NAME}" ] && [ "${SFX}" = "-1" ]; then
     diff -urN "${OLD_DIR_NAME}" "${DIR_NAME}" > \
               "${TEMP_DIR}/__${PACKAGE}_${OLD_VER_FULL}::${NEW_VER_FULL}.diff"
 fi
@@ -63,22 +71,21 @@ echo ;
 
 # About --buildinfo-option="-O" see at: https://bugs.debian.org/853795#10
 
-export DIST="${MAIN_DIST}"
 if [ "${SFX}" = "-1" ]; then
-    dch -b --force-distribution --distribution "${DIST}" -v "${EPOCH}${NEW_VER_FULL}" \
+    dch -b --force-distribution --distribution "${MAIN_DIST}" -v "${EPOCH}${NEW_VER_FULL}" \
         "${UPDATE_STRING}"
-    kwrite debian/changelog
+    kwrite debian/changelog &> /dev/null
     nice -n19 debuild -S -sa -d --buildinfo-option="-O" || exit 1
 else
-    dch -b --force-distribution --distribution "${DIST}" -v "${EPOCH}${NEW_VER_FULL}" \
+    dch -b --force-distribution --distribution "${MAIN_DIST}" -v "${EPOCH}${NEW_VER_FULL}" \
         "Some fixes in package."
-    kwrite debian/changelog
+    kwrite debian/changelog &> /dev/null
     # debuild -S -sd --buildinfo-option="-O" || exit 1
     nice -n19 debuild -S -sa -d --buildinfo-option="-O" || exit 1
 fi
 
 
-if [ "${1}" = "fast" ]; then
+if [ "${FAST_UPLOAD}" = "true" ]; then
     echo ;
     echo "Fast upload (without tests)."
     echo ;
@@ -101,8 +108,9 @@ else
 
     export BUILD_LOG_FILE="${TEMP_DIR}/__${PACKAGE}-${NEW_VER_FULL}.build.log"
     export WARNINGS_LOG_FILE="${TEMP_DIR}/__${PACKAGE}-${NEW_VER_FULL}.warnings.log"
-    cd "${TEST_DIR}/${DIR_NAME}"
     echo ;
+
+    cd "${TEST_DIR}/${DIR_NAME}"
     echo "Start building packages..."
     if [ "${CLEAN_BUILD}" = "true" ]; then
         sudo time nice -n19 pdebuild --pbuilder cowbuilder \
@@ -131,23 +139,40 @@ else
     grep "X: " "${LINTIAN_LOG_FILE}"
     echo "Finished running lintian."
     echo ;
-    kwrite ${LINTIAN_LOG_FILE}
+    kwrite ${LINTIAN_LOG_FILE} &> /dev/null
 
     cd "${TEMP_DIR}/${DIR_NAME}"
 fi
 
 
-kwrite debian/changelog
+kwrite debian/changelog &> /dev/null
 
 
 cd "${TEMP_DIR}"
 cp -fr "${DIR_NAME}/debian" "${PKG_DIR}/${PACKAGE}-debian/"
 
-echo "Update finished successfully"
+
+echo "Update finished successfully!"
+
+
+if [ "${TARGETED_TO_NEW_QUEUE}" = "true" ]; then
+    cd "${TEST_DIR}"
+    ARCHITECTURE="$(dpkg --print-architecture)"
+    debsign "${PACKAGE}_${NEW_VER_FULL}_${ARCHITECTURE}.changes"
+    echo "Package is targeted into NEW queue, so binary upload is required:"
+    echo "dput -f ftp-eu ${PACKAGE}_${NEW_VER_FULL}_${ARCHITECTURE}.changes"
+else
+    cd "${TEMP_DIR}"
+    echo "Sorce-only upload:"
+    echo "dput -f ftp-eu ${PACKAGE}_${NEW_VER_FULL}_source.changes"
+fi
+
+
+konsole &> /dev/null &
 
 
 # Local repo
-if [ "${1}" != "fast" ]; then
+if [ "${FAST_UPLOAD}" != "true" ]; then
     export APT_DIR="${MAIN_DIR}/LocalRepo"
     mkdir -p "${APT_DIR}/${PACKAGE}/"
     rm -f "${APT_DIR}/${PACKAGE}"/*.deb
