All package scripts were updated.

diff --git a/Launchpad/setting_variables b/Launchpad/setting_variables
--- a/Launchpad/setting_variables
+++ b/Launchpad/setting_variables
@@ -21,6 +21,43 @@ mkdir -p "${TEMP_DIR}"
 cd "${TEMP_DIR}" || exit 1
 
 
+# Get old version
+GetOldVersion()
+{
+    export OLD_VER_FULL=$(head -n 1 "${PKG_DIR}/${PACKAGE}-debian/debian/changelog" | sed -e "s/.* (\(.*\)) .*/\1/")
+    export OLD_VER=$(echo ${OLD_VER_FULL} | sed -e "s/^\(.*\)-[0-9]ppa.*$/\1/")
+    export OLD_SFX=$(echo ${OLD_VER_FULL} | sed -e "s/^.*\(-[0-9]ppa[0-9]\).*$/\1/")
+}
+
+
+# Display versions
+DisplayVersions()
+{
+    echo ;
+    echo "${1}"
+    echo ;
+    echo "On $(echo \"${1}\" | cut -f 3 -d /) now available such versions:"
+    echo "${VER_LIST}" | sort -r -V | head -n10
+    echo ;
+
+    echo "OLD_VER = ${OLD_VER}"
+    echo "NEW_VER = ${NEW_VER}"
+    echo "OLD_VER_FULL = ${OLD_VER_FULL}"
+    echo "NEW_VER_FULL = ${NEW_VER_FULL}"
+    echo ;
+}
+
+
+# Display versions for unstable packages
+DisplayVersionsUnstable()
+{
+    echo "Old  commit: ${OLD_COMMIT}"
+    echo "Last commit: ${LAST_COMMIT}"
+    echo "OLD_VER_FULL = ${OLD_VER_FULL}"
+    echo "NEW_VER_FULL = ${NEW_VER_FULL}"
+}
+
+
 # Print versions
 PrintVersions()
 {
@@ -74,5 +111,62 @@ if [ "${1}" = "print-versions" ]; then
         exit 0
     fi
 fi
+}
+
+
+# Check versions
+CheckVersions()
+{
+    if [ -z "${NEW_VER}" ]; then
+        echo "NEW_VER is empty!";
+        exit 1;
+    elif [ -z "${OLD_VER_FULL}" ]; then
+        echo "OLD_VER_FULL is empty!";
+        exit 1;
+    elif [ "${NEW_VER_FULL}" = "${OLD_VER_FULL}" ]; then
+        echo "Upgrading is not required.";
+        exit 0;
+    else
+        if [ "${NEW_VER}" != "${OLD_VER}" ]; then
+            if [ "${SFX}" != "-0ppa1" ]; then
+                echo "Now SFX = ${SFX} but must be '-0ppa1' for a new release!";
+                exit 0;
+            fi
+        else
+            if [ "${SFX}" = "-0ppa1" ]; then
+                echo "Now SFX = ${SFX} but OLD_SFX = ${OLD_SFX}.";
+                echo "Upgrading is not required.";
+                exit 0;
+            fi
+        fi
+    fi
+}
+
+
+# Check versions for unstable packages
+CheckVersionsUnstable()
+{
+    if [ -z "${OLD_COMMIT}" ]; then
+        echo "OLD_COMMIT is empty!";
+        exit 1;
+    elif [ -z "${LAST_COMMIT}" ]; then
+        echo "LAST_COMMIT is empty!";
+        exit 1;
+    elif [ -z ${CUR_VER} ]; then
+        echo "CUR_VER is empty!";
+        exit 1;
+    else
+        if [ "${LAST_COMMIT}" != "${OLD_COMMIT}" ]; then
+            if [ "${SFX}" != "-0ppa1" ]; then
+                echo "Now SFX = ${SFX} but must be '-0ppa1' for a new release!";
+                exit 0;
+            fi
+        else
+            if [ "${SFX}" = "-0ppa1" ]; then
+                echo "Upgrading is not required.";
+                exit 0;
+            fi
+        fi
+    fi
 }
 
